### ISSUE TITLE
Error pulling repository during brew install

### ISSUE THREAD

**Issue by masonoise** [codeclimate/homebrew-formulae#12]
This could be a possible sporadic error, so I'll try again in a little while, but just in case not:

```
$ brew install codeclimate
==> Installing codeclimate from codeclimate/homebrew-formulae
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.1.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/codeclimate-0.1.2.tar.gz
==> env PATH=/usr/local/bin:/usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin PREFIX=/usr/local/Cellar/codeclimat
bin/check
docker pull codeclimate/codeclimate:latest
Pulling repository codeclimate/codeclimate
time="2015-07-23T14:01:54-07:00" level="fatal" msg="Get https://index.docker.io/v1/repositories/codeclimate/codeclimate/images: dial tcp: lookup index.docker.io on 172.16.5.1:53: read udp 172.16.5.1:53: i/o timeout"
make: *** [install] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/codeclimate/homebrew-formulae/issues
```

I verified that a lookup of index.docker.io works as expected, but it may be a docker.io issue, of course. I'll report back if I retry later and it works correctly.

**Comment by gdiggs** [comment]
@masonoise I see this sometimes when pulling docker containers and using boot2docker. It seems that boot2docker loses network capabilities. If you restart boot2docker (`boot2docker stop && boot2docker start`), does it work? Are you able to pull other docker images?

**Comment by masonoise** [comment]
Good call -- I've seen that too, and I should have tried this first but the i/o timeout threw me off. That did indeed fix the problem. Thanks for the quick reply!
