### ISSUE TITLE
`brew upgrade codeclimate` fails - registry-1.docker.io: no such host

### ISSUE THREAD

**Issue by soderlind** [codeclimate/homebrew-formulae#20]
Environment:
- Mac OS X El Capitan 10.11.1
- docker-machine version 0.5.0 (04cfa58)
- [docker machine parallels driver](https://github.com/Parallels/docker-machine-parallels/)
- parallels 11 pro version 11.0.2 (31348)
- docker version 1.9.0

Error:

``` log
Pulling repository docker.io/codeclimate/codeclimate
Get https://registry-1.docker.io/v1/repositories/codeclimate/codeclimate/tags/latest: 
dial tcp: lookup registry-1.docker.io: no such host
make: *** [install] Error 1
```

**Comment by dblandin** [comment]
@soderlind This looks very similar to codeclimate/codeclimate#166. Could you try running through the troubleshooting in that issue and see if the problem persists?

**Comment by soderlind** [comment]
Yepp,  codeclimate/codeclimate#166 fixed the issue, I had old environments variables set in .zshrc for an old boot2docker installation. Thank you!

**Comment by dblandin** [comment]
No problem! Glad it was the same issue! :+1:
