### ISSUE TITLE
0,42.1 installation fails

### ISSUE THREAD

**Issue by soderlind** [codeclimate/homebrew-formulae#27]
I'm getting the following error:

```bash
brew upgrade `brew outdated`                                
==> Upgrading 1 outdated package, with result:
codeclimate/formulae/codeclimate 0.42.1
==> Upgrading codeclimate/formulae/codeclimate
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.42.1.tar.g
Already downloaded: /Users/per/Library/Caches/Homebrew/codeclimate-0.42.1.tar.gz
==> make install
Last 15 lines from /Users/per/Library/Logs/Homebrew/codeclimate/01.make:
2016-11-15 13:11:32 +0100

make
install

bin/check
docker pull codeclimate/codeclimate:latest
Pulling repository docker.io/codeclimate/codeclimate
Network timed out while trying to connect to https://index.docker.io/v1/repositories/codeclimate/codeclimate/images. You may want to check your internet connection or if you are behind a proxy.
make: *** [install] Error 1
```

Doing a `GET` at https://index.docker.io/v1/repositories/codeclimate/codeclimate/images returns an empty array: `[]`

**Comment by wfleming** [comment]
Hi @soderlind,

Are you using `docker-machine` or Docker for Mac? On `docker-machine` setups, we've seen the Docker VM lose external network connectivity at times. We haven't yet seen that happen with Docker for Mac, but theoretically it could be vulnerable to the same flaw.

In these cases, we suggest restarting your Docker VM, and trying again.

If it doesn't work after restarting the Docker VM, please try running `docker pull codeclimate/codeclimate:latest`, which is what that build script is actually running.

**Comment by soderlind** [comment]
I'm running Docker 1.12.3-beta30 for Mac. I get the same error even after disabling the firewall, restarting my mac and restarting docker.

``` bash
~ » docker pull codeclimate/codeclimate:latest        
Pulling repository docker.io/codeclimate/codeclimate
Network timed out while trying to connect to https://index.docker.io/v1/repositories/codeclimate/codeclimate/images. You may want to check your internet connection or if you are behind a proxy.
```

**Comment by wfleming** [comment]
Can you pull other public images, e.g. `docker pull hello-world`?

**Comment by soderlind** [comment]
No, so the problem is on my side. ... sorry.

**Comment by wfleming** [comment]
I'm going to go ahead & close this, @soderlind. I'm sorry the restart suggestion didn't help, and this particular connection issue isn't one I'm familiar with. Docker's forums might have folks who have seen similar setup issues before!

You mentioned disabling your firewall. If you're actively using a proxy or a VPN, those would probably be worth inspecting the settings of as well.

**Comment by soderlind** [comment]
FYI: I've been on the Docker beta program from the first beta release and hence where still on the beta program (Docker 1.12.3-beta30 for Mac). I uninstalled the beta and installed the stable release (Docker 1.12.3 for Mac) and presto! Doing a docker pull works again :)
