### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by kkirsche** [codeclimate/homebrew-formulae#5]
Hey guys,

Unlinked old codeclimate to update the homebrew installation of it. After doing so I can no longer install to the boot2docker container. Below are the commands which I am trying to use.

``` console
~ ❯❯❯ boot2docker up
Waiting for VM and Docker daemon to start...
.o
Started.
Writing /Users/username/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/username/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/username/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.

~ ❯❯❯ boot2docker shellinit
Writing /Users/username/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/username/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/username/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.

~ ❯❯❯ brew install codeclimate
==> Installing codeclimate from codeclimate/homebrew-formulae
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.0.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/codeclimate-0.0.7.tar.gz
==> env PATH=/usr/local/bin:/usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin PRE
bin/check
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/version: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103
Unable to run `docker version', the docker daemon may not be running
Please ensure `boot2docker up' succeeds and you've run `boot2docker shellinit' in this shell
make: *** [install] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/codeclimate/homebrew-formulae/issues
```

`docker version` results in:

``` console
~ ❯❯❯ docker version                                                                  ⏎
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/version: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103
```

Would this be a boot2docker issue or is this an issue with this formula?

**Comment by pbrisbin** [comment]
Can you tell me what `which docker` says? It's possible the `docker version` being run in the formula is a different one than when you run outside of it -- I notice you're using a newer client version (1.7) than we typically see (1.6) but that shouldn't cause this issue.

**Comment by kkirsche** [comment]
`which docker` results in:

``` console
~ ❯❯❯ which docker
/usr/local/bin/docker
```

Thanks for your help :smiley:

**Comment by pbrisbin** [comment]
Oh, I didn't notice that running `docker version` outside the formula still emits the same error. That does indicate it's a boot2docker setup issue and nothing (AFAICT) to do with the formula.

As a guess, I might try removing any docker environment variables from your shell startup file, opening a new terminal, and re-running `shellinit`. It looks like the certs you have aren't valid, so you need to somehow trigger the use of new ones (I think).

Do you mind if I close this issue, since it doesn't seem to be related to the formula?

**Comment by kkirsche** [comment]
Not at all. I just was trying to identify where the issue was (e.g. formula or boot2docker). Strongly wish your tools didn't require docker as docker is a bit of a nightmare to deal with for these types of reasons, but at least it's not the formula.
